name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t jason2706/my-app:${{ github.sha }} .
        docker tag jason2706/my-app:${{ github.sha }} jason2706/my-app:latest

    - name: Push Docker image to Docker Hub
      run: |

        docker push jason2706/my-app:${{ github.sha }}
        docker push jason2706/my-app:latest

  deploy:
    needs: build  # This job runs after the build job is completed
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2  # Change to your AWS region

    - name: Update ECS Service with new Docker image
      run: |
        aws ecs update-service --cluster my-aws-cluster --service my-service --force-new-deployment --image jason2706/my-app:${{ github.sha }}
