name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t myusername/my-app:${{ github.sha }} .
        docker tag myusername/my-app:${{ github.sha }} myusername/my-app:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push myusername/my-app:${{ github.sha }}
        docker push myusername/my-app:latest
